version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: fluxstream
    main: ./cmd/fluxstream-cli/main.go
    binary: fluxstream
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: fluxstream-archive
    builds: [fluxstream]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: scythe504
    name: fluxstream
  footer: |
    ---
    Released by [GoReleaser](https://goreleaser.com)
