FROM golang:1.25.2-alpine AS builder

WORKDIR /app/fluxstream


COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /out/api ./cmd/api

FROM scratch

COPY --from=builder /out/api /api

EXPOSE 8080

CMD ["/api"]